# This file is part of the YAZ toolkit
# Copyright (C) Index Data
# See the file LICENSE for details.
#
#
# Converts a MRK / MarcMaker to C-source

proc mrktoc {csvfname cfname } {
    set csv [open $csvfname r]
    set cfile [open $cfname w]
    set lineno 0

    puts $cfile "/** \\file $cfname"
    puts $cfile "    \\brief MRK mappings: Generated by mrkconv.tcl from $csvfname */"
    puts $cfile {}
    puts $cfile "static const char *mappings = "
    while {1} {
        incr lineno
        set cnt [gets $csv line]
        if {$cnt < 0} {
            break
        }
        if {[regexp {^(\{[^,]*),([^,]*),} $line s pattern values]} {
            if {![string equal $values 00x]} {
                puts -nonewline $cfile "\"${pattern}"
                foreach v $values {
                    set ch [string range $v 0 1]
                    puts -nonewline $cfile "\\x$ch"
                }
                puts $cfile {"}
            }
        }
    }
    puts $cfile {}
    puts $cfile {;}
    puts $cfile "const char yaz_mrk_lookup(const char *pattern)"
    puts $cfile "\{"
    puts $cfile "   return strstr(mappings, pattern);"
    puts $cfile "\}"
    close $csv
    close $cfile
}

if {[llength $argv] != 2} {
    puts "Usage mrkconv.tcl infile cfile"
    exit 1
}
mrktoc [lindex $argv 0] [lindex $argv 1]
