CLCILLRequestExtension DEFINITIONS ::=
--The object identifier is 1.0.10161.13.2
BEGIN
IMPORTS ILL-String FROM ISO-10161-ILL-1;

OCLCILLRequestExtension ::=SEQUENCE {
    clientDepartment [0] ILL-String OPTIONAL,
    paymentMethod [1] ILL-String OPTIONAL,
    uniformTitle [2] ILL-String OPTIONAL,
    dissertation [3] ILL-String OPTIONAL,
    issueNumber [4] ILL-String OPTIONAL,
    volume [5] ILL-String OPTIONAL,
    affiliations [6] ILL-String OPTIONAL,
    source [7] ILL-String OPTIONAL
}
END

