# Build yaz from source
name: Build YAZ
on: [push, pull_request]
jobs:
 build-yaz:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
     with:
       fetch-depth: 1
   - name: Install required dependencies
     run: >
       sudo apt install autoconf automake libtool gcc make bison
       tclsh xsltproc docbook docbook-xml docbook-xsl
   - name: Run buildconf without xml, icu, ...
     run: ./buildconf.sh
   - name: Run configure without xml, icu, ...
     run: ./configure --without-xml2 --without-icu
   - name: Run Make check
     run: make -j4 check
   - name: Run Make dist
     run: make -j4 dist
   - name: Run Make clean
     run: make clean
   - name: Clean configure cache
     run: rm -f config.cache
   - name: Install optional depencies
     run: >
       sudo apt install pkg-config libxslt1-dev libgnutls28-dev
       libreadline-dev libwrap0-dev libicu-dev
   - name: Run configure  with xml, icu, ...
     run: ./configure
   - name: Run Make check with xml, icu, ...
     run: make -j4 check
